// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: mesh.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Mesh_Pair_FullMethodName         = "/mesh.v1.Mesh/Pair"
	Mesh_ApplyConfig_FullMethodName  = "/mesh.v1.Mesh/ApplyConfig"
	Mesh_AddClient_FullMethodName    = "/mesh.v1.Mesh/AddClient"
	Mesh_RemoveClient_FullMethodName = "/mesh.v1.Mesh/RemoveClient"
	Mesh_GetStats_FullMethodName     = "/mesh.v1.Mesh/GetStats"
	Mesh_Heartbeat_FullMethodName    = "/mesh.v1.Mesh/Heartbeat"
	Mesh_StreamLogs_FullMethodName   = "/mesh.v1.Mesh/StreamLogs"
)

// MeshClient is the client API for Mesh service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Mesh is the master <-> node control protocol.
//
// Transport: gRPC over TCP, mTLS in steady state. The single exception
// is `Pair` which runs over plain TLS bootstrapped from a one-shot
// pairing token; subsequent calls require client cert authentication.
//
// Master is always the gRPC client; the node is always the server.
// This means master can sit behind NAT (typical: a panel behind
// Cloudflare) and nodes are the public-facing data plane.
type MeshClient interface {
	// Pair establishes mutual trust between a master and a fresh node.
	// Called exactly once per node, immediately after the operator
	// creates the node row on the master and pastes the bootstrap token
	// shown by the node.
	//
	// Authentication: the node's TLS cert is validated by the master
	// against the SHA-256 fingerprint embedded in the bootstrap token.
	// This is the only time the master accepts a self-signed leaf
	// without a pinned CA. After Pair returns, both sides pin certs
	// and all subsequent calls require mTLS.
	Pair(ctx context.Context, in *PairRequest, opts ...grpc.CallOption) (*PairResponse, error)
	// ApplyConfig pushes a complete xray-core config to the node. The
	// node MUST atomically swap and reload — partial application is not
	// allowed. Idempotent: same config_hash → no-op.
	ApplyConfig(ctx context.Context, in *ApplyConfigRequest, opts ...grpc.CallOption) (*ApplyConfigResponse, error)
	// AddClient / RemoveClient mirror xray HandlerService for fast,
	// single-client mutations that don't require an xray reload.
	// Used by master when an inbound is not changing structurally —
	// just gaining/losing a user. Falls back to ApplyConfig on failure.
	AddClient(ctx context.Context, in *ClientOp, opts ...grpc.CallOption) (*OpResult, error)
	RemoveClient(ctx context.Context, in *ClientOp, opts ...grpc.CallOption) (*OpResult, error)
	// GetStats mirrors xray StatsService. Master polls periodically and
	// aggregates per-(client, node) counters into the local DB.
	GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	// Heartbeat: bidirectional liveness + drift detection. Master sends
	// its current desired-config hash; node sends its applied hash and
	// local xray status. If hashes diverge for >N pings, master
	// re-sends ApplyConfig.
	Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatPing, HeartbeatPong], error)
	// StreamLogs: tail xray + panel logs to the master operator. Used
	// for the Nodes UI debug pane. Closing the stream terminates the
	// tail.
	StreamLogs(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error)
}

type meshClient struct {
	cc grpc.ClientConnInterface
}

func NewMeshClient(cc grpc.ClientConnInterface) MeshClient {
	return &meshClient{cc}
}

func (c *meshClient) Pair(ctx context.Context, in *PairRequest, opts ...grpc.CallOption) (*PairResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PairResponse)
	err := c.cc.Invoke(ctx, Mesh_Pair_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshClient) ApplyConfig(ctx context.Context, in *ApplyConfigRequest, opts ...grpc.CallOption) (*ApplyConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyConfigResponse)
	err := c.cc.Invoke(ctx, Mesh_ApplyConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshClient) AddClient(ctx context.Context, in *ClientOp, opts ...grpc.CallOption) (*OpResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpResult)
	err := c.cc.Invoke(ctx, Mesh_AddClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshClient) RemoveClient(ctx context.Context, in *ClientOp, opts ...grpc.CallOption) (*OpResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpResult)
	err := c.cc.Invoke(ctx, Mesh_RemoveClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshClient) GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, Mesh_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshClient) Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatPing, HeartbeatPong], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Mesh_ServiceDesc.Streams[0], Mesh_Heartbeat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HeartbeatPing, HeartbeatPong]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Mesh_HeartbeatClient = grpc.BidiStreamingClient[HeartbeatPing, HeartbeatPong]

func (c *meshClient) StreamLogs(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Mesh_ServiceDesc.Streams[1], Mesh_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogRequest, LogChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Mesh_StreamLogsClient = grpc.ServerStreamingClient[LogChunk]

// MeshServer is the server API for Mesh service.
// All implementations must embed UnimplementedMeshServer
// for forward compatibility.
//
// Mesh is the master <-> node control protocol.
//
// Transport: gRPC over TCP, mTLS in steady state. The single exception
// is `Pair` which runs over plain TLS bootstrapped from a one-shot
// pairing token; subsequent calls require client cert authentication.
//
// Master is always the gRPC client; the node is always the server.
// This means master can sit behind NAT (typical: a panel behind
// Cloudflare) and nodes are the public-facing data plane.
type MeshServer interface {
	// Pair establishes mutual trust between a master and a fresh node.
	// Called exactly once per node, immediately after the operator
	// creates the node row on the master and pastes the bootstrap token
	// shown by the node.
	//
	// Authentication: the node's TLS cert is validated by the master
	// against the SHA-256 fingerprint embedded in the bootstrap token.
	// This is the only time the master accepts a self-signed leaf
	// without a pinned CA. After Pair returns, both sides pin certs
	// and all subsequent calls require mTLS.
	Pair(context.Context, *PairRequest) (*PairResponse, error)
	// ApplyConfig pushes a complete xray-core config to the node. The
	// node MUST atomically swap and reload — partial application is not
	// allowed. Idempotent: same config_hash → no-op.
	ApplyConfig(context.Context, *ApplyConfigRequest) (*ApplyConfigResponse, error)
	// AddClient / RemoveClient mirror xray HandlerService for fast,
	// single-client mutations that don't require an xray reload.
	// Used by master when an inbound is not changing structurally —
	// just gaining/losing a user. Falls back to ApplyConfig on failure.
	AddClient(context.Context, *ClientOp) (*OpResult, error)
	RemoveClient(context.Context, *ClientOp) (*OpResult, error)
	// GetStats mirrors xray StatsService. Master polls periodically and
	// aggregates per-(client, node) counters into the local DB.
	GetStats(context.Context, *StatsRequest) (*StatsResponse, error)
	// Heartbeat: bidirectional liveness + drift detection. Master sends
	// its current desired-config hash; node sends its applied hash and
	// local xray status. If hashes diverge for >N pings, master
	// re-sends ApplyConfig.
	Heartbeat(grpc.BidiStreamingServer[HeartbeatPing, HeartbeatPong]) error
	// StreamLogs: tail xray + panel logs to the master operator. Used
	// for the Nodes UI debug pane. Closing the stream terminates the
	// tail.
	StreamLogs(*LogRequest, grpc.ServerStreamingServer[LogChunk]) error
	mustEmbedUnimplementedMeshServer()
}

// UnimplementedMeshServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeshServer struct{}

func (UnimplementedMeshServer) Pair(context.Context, *PairRequest) (*PairResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Pair not implemented")
}
func (UnimplementedMeshServer) ApplyConfig(context.Context, *ApplyConfigRequest) (*ApplyConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyConfig not implemented")
}
func (UnimplementedMeshServer) AddClient(context.Context, *ClientOp) (*OpResult, error) {
	return nil, status.Error(codes.Unimplemented, "method AddClient not implemented")
}
func (UnimplementedMeshServer) RemoveClient(context.Context, *ClientOp) (*OpResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveClient not implemented")
}
func (UnimplementedMeshServer) GetStats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedMeshServer) Heartbeat(grpc.BidiStreamingServer[HeartbeatPing, HeartbeatPong]) error {
	return status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedMeshServer) StreamLogs(*LogRequest, grpc.ServerStreamingServer[LogChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedMeshServer) mustEmbedUnimplementedMeshServer() {}
func (UnimplementedMeshServer) testEmbeddedByValue()              {}

// UnsafeMeshServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeshServer will
// result in compilation errors.
type UnsafeMeshServer interface {
	mustEmbedUnimplementedMeshServer()
}

func RegisterMeshServer(s grpc.ServiceRegistrar, srv MeshServer) {
	// If the following call panics, it indicates UnimplementedMeshServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Mesh_ServiceDesc, srv)
}

func _Mesh_Pair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServer).Pair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mesh_Pair_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServer).Pair(ctx, req.(*PairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mesh_ApplyConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServer).ApplyConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mesh_ApplyConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServer).ApplyConfig(ctx, req.(*ApplyConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mesh_AddClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientOp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServer).AddClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mesh_AddClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServer).AddClient(ctx, req.(*ClientOp))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mesh_RemoveClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientOp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServer).RemoveClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mesh_RemoveClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServer).RemoveClient(ctx, req.(*ClientOp))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mesh_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mesh_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServer).GetStats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mesh_Heartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MeshServer).Heartbeat(&grpc.GenericServerStream[HeartbeatPing, HeartbeatPong]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Mesh_HeartbeatServer = grpc.BidiStreamingServer[HeartbeatPing, HeartbeatPong]

func _Mesh_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MeshServer).StreamLogs(m, &grpc.GenericServerStream[LogRequest, LogChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Mesh_StreamLogsServer = grpc.ServerStreamingServer[LogChunk]

// Mesh_ServiceDesc is the grpc.ServiceDesc for Mesh service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mesh_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mesh.v1.Mesh",
	HandlerType: (*MeshServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pair",
			Handler:    _Mesh_Pair_Handler,
		},
		{
			MethodName: "ApplyConfig",
			Handler:    _Mesh_ApplyConfig_Handler,
		},
		{
			MethodName: "AddClient",
			Handler:    _Mesh_AddClient_Handler,
		},
		{
			MethodName: "RemoveClient",
			Handler:    _Mesh_RemoveClient_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _Mesh_GetStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Heartbeat",
			Handler:       _Mesh_Heartbeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamLogs",
			Handler:       _Mesh_StreamLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mesh.proto",
}
