// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: mesh.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PairRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Plaintext bootstrap token shown to the operator on the node UI.
	// Single-use, ~10min TTL, ~32 random bytes base64-encoded. The node
	// verifies by constant-time compare against the value in its
	// node_identities row.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// PEM-encoded master CA certificate. Pinned by the node; used to
	// validate the master's mTLS client cert on every subsequent call.
	MasterCaPem []byte `protobuf:"bytes,2,opt,name=master_ca_pem,json=masterCaPem,proto3" json:"master_ca_pem,omitempty"`
	// PEM-encoded master client CSR. The node signs it with its own CA
	// and returns the cert in PairResponse.
	MasterClientCsrPem []byte `protobuf:"bytes,3,opt,name=master_client_csr_pem,json=masterClientCsrPem,proto3" json:"master_client_csr_pem,omitempty"`
	// Human-readable master display name, used in the node's status UI.
	MasterName    string `protobuf:"bytes,4,opt,name=master_name,json=masterName,proto3" json:"master_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairRequest) Reset() {
	*x = PairRequest{}
	mi := &file_mesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairRequest) ProtoMessage() {}

func (x *PairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairRequest.ProtoReflect.Descriptor instead.
func (*PairRequest) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{0}
}

func (x *PairRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PairRequest) GetMasterCaPem() []byte {
	if x != nil {
		return x.MasterCaPem
	}
	return nil
}

func (x *PairRequest) GetMasterClientCsrPem() []byte {
	if x != nil {
		return x.MasterClientCsrPem
	}
	return nil
}

func (x *PairRequest) GetMasterName() string {
	if x != nil {
		return x.MasterName
	}
	return ""
}

type PairResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PEM-encoded node CA cert. Pinned by master; used to validate the
	// node's gRPC server cert on every subsequent call.
	NodeCaPem []byte `protobuf:"bytes,1,opt,name=node_ca_pem,json=nodeCaPem,proto3" json:"node_ca_pem,omitempty"`
	// Master's client cert, signed by node CA, returned to master.
	SignedMasterClientCertPem []byte `protobuf:"bytes,2,opt,name=signed_master_client_cert_pem,json=signedMasterClientCertPem,proto3" json:"signed_master_client_cert_pem,omitempty"`
	// Node-reported metadata.
	NodeName      string `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	NodeVersion   string `protobuf:"bytes,4,opt,name=node_version,json=nodeVersion,proto3" json:"node_version,omitempty"`
	XrayVersion   string `protobuf:"bytes,5,opt,name=xray_version,json=xrayVersion,proto3" json:"xray_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairResponse) Reset() {
	*x = PairResponse{}
	mi := &file_mesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairResponse) ProtoMessage() {}

func (x *PairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairResponse.ProtoReflect.Descriptor instead.
func (*PairResponse) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{1}
}

func (x *PairResponse) GetNodeCaPem() []byte {
	if x != nil {
		return x.NodeCaPem
	}
	return nil
}

func (x *PairResponse) GetSignedMasterClientCertPem() []byte {
	if x != nil {
		return x.SignedMasterClientCertPem
	}
	return nil
}

func (x *PairResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *PairResponse) GetNodeVersion() string {
	if x != nil {
		return x.NodeVersion
	}
	return ""
}

func (x *PairResponse) GetXrayVersion() string {
	if x != nil {
		return x.XrayVersion
	}
	return ""
}

type ApplyConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SHA-256 hex of config_json. Lets the node early-out if the config
	// is identical to what's already running.
	ConfigHash string `protobuf:"bytes,1,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	// Full xray-core config JSON. Same shape that 3x-ui already writes
	// to /usr/local/x-ui/bin/config.json — we ship that exact bytes
	// through the wire so the node-side translator is trivial.
	ConfigJson    []byte `protobuf:"bytes,2,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyConfigRequest) Reset() {
	*x = ApplyConfigRequest{}
	mi := &file_mesh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyConfigRequest) ProtoMessage() {}

func (x *ApplyConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyConfigRequest.ProtoReflect.Descriptor instead.
func (*ApplyConfigRequest) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{2}
}

func (x *ApplyConfigRequest) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

func (x *ApplyConfigRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

type ApplyConfigResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Applied        bool                   `protobuf:"varint,1,opt,name=applied,proto3" json:"applied,omitempty"`                                     // true if the node restarted xray with the new config
	AlreadyCurrent bool                   `protobuf:"varint,2,opt,name=already_current,json=alreadyCurrent,proto3" json:"already_current,omitempty"` // true if config_hash matched the running one (no-op)
	XrayVersion    string                 `protobuf:"bytes,3,opt,name=xray_version,json=xrayVersion,proto3" json:"xray_version,omitempty"`
	Error          string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplyConfigResponse) Reset() {
	*x = ApplyConfigResponse{}
	mi := &file_mesh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyConfigResponse) ProtoMessage() {}

func (x *ApplyConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyConfigResponse.ProtoReflect.Descriptor instead.
func (*ApplyConfigResponse) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{3}
}

func (x *ApplyConfigResponse) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *ApplyConfigResponse) GetAlreadyCurrent() bool {
	if x != nil {
		return x.AlreadyCurrent
	}
	return false
}

func (x *ApplyConfigResponse) GetXrayVersion() string {
	if x != nil {
		return x.XrayVersion
	}
	return ""
}

func (x *ApplyConfigResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ClientOp struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	InboundTag string                 `protobuf:"bytes,1,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	Protocol   string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"` // matches model.Protocol values
	// Protocol-specific user blob. Mirrors what xray HandlerService's
	// AddUser/RemoveUser expects. JSON-encoded for transport simplicity;
	// master constructs this from model.Client + flow info before send.
	UserJson      []byte `protobuf:"bytes,3,opt,name=user_json,json=userJson,proto3" json:"user_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientOp) Reset() {
	*x = ClientOp{}
	mi := &file_mesh_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientOp) ProtoMessage() {}

func (x *ClientOp) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientOp.ProtoReflect.Descriptor instead.
func (*ClientOp) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{4}
}

func (x *ClientOp) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

func (x *ClientOp) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ClientOp) GetUserJson() []byte {
	if x != nil {
		return x.UserJson
	}
	return nil
}

type OpResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpResult) Reset() {
	*x = OpResult{}
	mi := &file_mesh_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpResult) ProtoMessage() {}

func (x *OpResult) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpResult.ProtoReflect.Descriptor instead.
func (*OpResult) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{5}
}

func (x *OpResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *OpResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If true, atomically read-and-zero the counters. Master uses true
	// for periodic delta polling.
	Reset_ bool `protobuf:"varint,1,opt,name=reset,proto3" json:"reset,omitempty"`
	// xray stats name pattern (e.g. "user>>>foo@bar>>>traffic>>>uplink").
	// Empty means "all".
	Pattern       string `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_mesh_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{6}
}

func (x *StatsRequest) GetReset_() bool {
	if x != nil {
		return x.Reset_
	}
	return false
}

func (x *StatsRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

type StatRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRow) Reset() {
	*x = StatRow{}
	mi := &file_mesh_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRow) ProtoMessage() {}

func (x *StatRow) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRow.ProtoReflect.Descriptor instead.
func (*StatRow) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{7}
}

func (x *StatRow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatRow) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*StatRow             `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_mesh_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{8}
}

func (x *StatsResponse) GetRows() []*StatRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type HeartbeatPing struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TsUnixMs          int64                  `protobuf:"varint,1,opt,name=ts_unix_ms,json=tsUnixMs,proto3" json:"ts_unix_ms,omitempty"`
	AppliedConfigHash string                 `protobuf:"bytes,2,opt,name=applied_config_hash,json=appliedConfigHash,proto3" json:"applied_config_hash,omitempty"`
	XrayStatus        string                 `protobuf:"bytes,3,opt,name=xray_status,json=xrayStatus,proto3" json:"xray_status,omitempty"` // "running" | "stopped" | "errored"
	LoadAvg_1M        float64                `protobuf:"fixed64,4,opt,name=load_avg_1m,json=loadAvg1m,proto3" json:"load_avg_1m,omitempty"`
	MemUsedBytes      uint64                 `protobuf:"varint,5,opt,name=mem_used_bytes,json=memUsedBytes,proto3" json:"mem_used_bytes,omitempty"`
	MemTotalBytes     uint64                 `protobuf:"varint,6,opt,name=mem_total_bytes,json=memTotalBytes,proto3" json:"mem_total_bytes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatPing) Reset() {
	*x = HeartbeatPing{}
	mi := &file_mesh_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPing) ProtoMessage() {}

func (x *HeartbeatPing) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPing.ProtoReflect.Descriptor instead.
func (*HeartbeatPing) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatPing) GetTsUnixMs() int64 {
	if x != nil {
		return x.TsUnixMs
	}
	return 0
}

func (x *HeartbeatPing) GetAppliedConfigHash() string {
	if x != nil {
		return x.AppliedConfigHash
	}
	return ""
}

func (x *HeartbeatPing) GetXrayStatus() string {
	if x != nil {
		return x.XrayStatus
	}
	return ""
}

func (x *HeartbeatPing) GetLoadAvg_1M() float64 {
	if x != nil {
		return x.LoadAvg_1M
	}
	return 0
}

func (x *HeartbeatPing) GetMemUsedBytes() uint64 {
	if x != nil {
		return x.MemUsedBytes
	}
	return 0
}

func (x *HeartbeatPing) GetMemTotalBytes() uint64 {
	if x != nil {
		return x.MemTotalBytes
	}
	return 0
}

type HeartbeatPong struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TsUnixMs int64                  `protobuf:"varint,1,opt,name=ts_unix_ms,json=tsUnixMs,proto3" json:"ts_unix_ms,omitempty"`
	// Master's view of the desired config hash. If this differs from
	// the node's last applied hash for too long, node should expect an
	// imminent ApplyConfig call.
	DesiredConfigHash string `protobuf:"bytes,2,opt,name=desired_config_hash,json=desiredConfigHash,proto3" json:"desired_config_hash,omitempty"`
	// Soft signal: master telling node it should/shouldn't have xray
	// running. v1: always true while the node row exists on master.
	XrayShouldBeRunning bool `protobuf:"varint,3,opt,name=xray_should_be_running,json=xrayShouldBeRunning,proto3" json:"xray_should_be_running,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HeartbeatPong) Reset() {
	*x = HeartbeatPong{}
	mi := &file_mesh_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPong) ProtoMessage() {}

func (x *HeartbeatPong) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPong.ProtoReflect.Descriptor instead.
func (*HeartbeatPong) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatPong) GetTsUnixMs() int64 {
	if x != nil {
		return x.TsUnixMs
	}
	return 0
}

func (x *HeartbeatPong) GetDesiredConfigHash() string {
	if x != nil {
		return x.DesiredConfigHash
	}
	return ""
}

func (x *HeartbeatPong) GetXrayShouldBeRunning() bool {
	if x != nil {
		return x.XrayShouldBeRunning
	}
	return false
}

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`                         // "xray" | "panel" | "access"
	Follow        bool                   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`                        // tail -f if true
	TailLines     int32                  `protobuf:"varint,3,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"` // initial backlog, 0 = none
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_mesh_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{11}
}

func (x *LogRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *LogRequest) GetTailLines() int32 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

type LogChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // raw bytes, may contain partial lines
	TsUnixMs      int64                  `protobuf:"varint,2,opt,name=ts_unix_ms,json=tsUnixMs,proto3" json:"ts_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_mesh_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{12}
}

func (x *LogChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LogChunk) GetTsUnixMs() int64 {
	if x != nil {
		return x.TsUnixMs
	}
	return 0
}

var File_mesh_proto protoreflect.FileDescriptor

const file_mesh_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"mesh.proto\x12\amesh.v1\"\x9b\x01\n" +
	"\vPairRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\"\n" +
	"\rmaster_ca_pem\x18\x02 \x01(\fR\vmasterCaPem\x121\n" +
	"\x15master_client_csr_pem\x18\x03 \x01(\fR\x12masterClientCsrPem\x12\x1f\n" +
	"\vmaster_name\x18\x04 \x01(\tR\n" +
	"masterName\"\xd3\x01\n" +
	"\fPairResponse\x12\x1e\n" +
	"\vnode_ca_pem\x18\x01 \x01(\fR\tnodeCaPem\x12@\n" +
	"\x1dsigned_master_client_cert_pem\x18\x02 \x01(\fR\x19signedMasterClientCertPem\x12\x1b\n" +
	"\tnode_name\x18\x03 \x01(\tR\bnodeName\x12!\n" +
	"\fnode_version\x18\x04 \x01(\tR\vnodeVersion\x12!\n" +
	"\fxray_version\x18\x05 \x01(\tR\vxrayVersion\"V\n" +
	"\x12ApplyConfigRequest\x12\x1f\n" +
	"\vconfig_hash\x18\x01 \x01(\tR\n" +
	"configHash\x12\x1f\n" +
	"\vconfig_json\x18\x02 \x01(\fR\n" +
	"configJson\"\x91\x01\n" +
	"\x13ApplyConfigResponse\x12\x18\n" +
	"\aapplied\x18\x01 \x01(\bR\aapplied\x12'\n" +
	"\x0falready_current\x18\x02 \x01(\bR\x0ealreadyCurrent\x12!\n" +
	"\fxray_version\x18\x03 \x01(\tR\vxrayVersion\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"d\n" +
	"\bClientOp\x12\x1f\n" +
	"\vinbound_tag\x18\x01 \x01(\tR\n" +
	"inboundTag\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x1b\n" +
	"\tuser_json\x18\x03 \x01(\fR\buserJson\"0\n" +
	"\bOpResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\">\n" +
	"\fStatsRequest\x12\x14\n" +
	"\x05reset\x18\x01 \x01(\bR\x05reset\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\"3\n" +
	"\aStatRow\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\"5\n" +
	"\rStatsResponse\x12$\n" +
	"\x04rows\x18\x01 \x03(\v2\x10.mesh.v1.StatRowR\x04rows\"\xec\x01\n" +
	"\rHeartbeatPing\x12\x1c\n" +
	"\n" +
	"ts_unix_ms\x18\x01 \x01(\x03R\btsUnixMs\x12.\n" +
	"\x13applied_config_hash\x18\x02 \x01(\tR\x11appliedConfigHash\x12\x1f\n" +
	"\vxray_status\x18\x03 \x01(\tR\n" +
	"xrayStatus\x12\x1e\n" +
	"\vload_avg_1m\x18\x04 \x01(\x01R\tloadAvg1m\x12$\n" +
	"\x0emem_used_bytes\x18\x05 \x01(\x04R\fmemUsedBytes\x12&\n" +
	"\x0fmem_total_bytes\x18\x06 \x01(\x04R\rmemTotalBytes\"\x92\x01\n" +
	"\rHeartbeatPong\x12\x1c\n" +
	"\n" +
	"ts_unix_ms\x18\x01 \x01(\x03R\btsUnixMs\x12.\n" +
	"\x13desired_config_hash\x18\x02 \x01(\tR\x11desiredConfigHash\x123\n" +
	"\x16xray_should_be_running\x18\x03 \x01(\bR\x13xrayShouldBeRunning\"[\n" +
	"\n" +
	"LogRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x03 \x01(\x05R\ttailLines\"<\n" +
	"\bLogChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1c\n" +
	"\n" +
	"ts_unix_ms\x18\x02 \x01(\x03R\btsUnixMs2\xa2\x03\n" +
	"\x04Mesh\x123\n" +
	"\x04Pair\x12\x14.mesh.v1.PairRequest\x1a\x15.mesh.v1.PairResponse\x12H\n" +
	"\vApplyConfig\x12\x1b.mesh.v1.ApplyConfigRequest\x1a\x1c.mesh.v1.ApplyConfigResponse\x121\n" +
	"\tAddClient\x12\x11.mesh.v1.ClientOp\x1a\x11.mesh.v1.OpResult\x124\n" +
	"\fRemoveClient\x12\x11.mesh.v1.ClientOp\x1a\x11.mesh.v1.OpResult\x129\n" +
	"\bGetStats\x12\x15.mesh.v1.StatsRequest\x1a\x16.mesh.v1.StatsResponse\x12?\n" +
	"\tHeartbeat\x12\x16.mesh.v1.HeartbeatPing\x1a\x16.mesh.v1.HeartbeatPong(\x010\x01\x126\n" +
	"\n" +
	"StreamLogs\x12\x13.mesh.v1.LogRequest\x1a\x11.mesh.v1.LogChunk0\x01B)Z'github.com/mhsanaei/3x-ui/v2/mesh/pb;pbb\x06proto3"

var (
	file_mesh_proto_rawDescOnce sync.Once
	file_mesh_proto_rawDescData []byte
)

func file_mesh_proto_rawDescGZIP() []byte {
	file_mesh_proto_rawDescOnce.Do(func() {
		file_mesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mesh_proto_rawDesc), len(file_mesh_proto_rawDesc)))
	})
	return file_mesh_proto_rawDescData
}

var file_mesh_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_mesh_proto_goTypes = []any{
	(*PairRequest)(nil),         // 0: mesh.v1.PairRequest
	(*PairResponse)(nil),        // 1: mesh.v1.PairResponse
	(*ApplyConfigRequest)(nil),  // 2: mesh.v1.ApplyConfigRequest
	(*ApplyConfigResponse)(nil), // 3: mesh.v1.ApplyConfigResponse
	(*ClientOp)(nil),            // 4: mesh.v1.ClientOp
	(*OpResult)(nil),            // 5: mesh.v1.OpResult
	(*StatsRequest)(nil),        // 6: mesh.v1.StatsRequest
	(*StatRow)(nil),             // 7: mesh.v1.StatRow
	(*StatsResponse)(nil),       // 8: mesh.v1.StatsResponse
	(*HeartbeatPing)(nil),       // 9: mesh.v1.HeartbeatPing
	(*HeartbeatPong)(nil),       // 10: mesh.v1.HeartbeatPong
	(*LogRequest)(nil),          // 11: mesh.v1.LogRequest
	(*LogChunk)(nil),            // 12: mesh.v1.LogChunk
}
var file_mesh_proto_depIdxs = []int32{
	7,  // 0: mesh.v1.StatsResponse.rows:type_name -> mesh.v1.StatRow
	0,  // 1: mesh.v1.Mesh.Pair:input_type -> mesh.v1.PairRequest
	2,  // 2: mesh.v1.Mesh.ApplyConfig:input_type -> mesh.v1.ApplyConfigRequest
	4,  // 3: mesh.v1.Mesh.AddClient:input_type -> mesh.v1.ClientOp
	4,  // 4: mesh.v1.Mesh.RemoveClient:input_type -> mesh.v1.ClientOp
	6,  // 5: mesh.v1.Mesh.GetStats:input_type -> mesh.v1.StatsRequest
	9,  // 6: mesh.v1.Mesh.Heartbeat:input_type -> mesh.v1.HeartbeatPing
	11, // 7: mesh.v1.Mesh.StreamLogs:input_type -> mesh.v1.LogRequest
	1,  // 8: mesh.v1.Mesh.Pair:output_type -> mesh.v1.PairResponse
	3,  // 9: mesh.v1.Mesh.ApplyConfig:output_type -> mesh.v1.ApplyConfigResponse
	5,  // 10: mesh.v1.Mesh.AddClient:output_type -> mesh.v1.OpResult
	5,  // 11: mesh.v1.Mesh.RemoveClient:output_type -> mesh.v1.OpResult
	8,  // 12: mesh.v1.Mesh.GetStats:output_type -> mesh.v1.StatsResponse
	10, // 13: mesh.v1.Mesh.Heartbeat:output_type -> mesh.v1.HeartbeatPong
	12, // 14: mesh.v1.Mesh.StreamLogs:output_type -> mesh.v1.LogChunk
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_mesh_proto_init() }
func file_mesh_proto_init() {
	if File_mesh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mesh_proto_rawDesc), len(file_mesh_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mesh_proto_goTypes,
		DependencyIndexes: file_mesh_proto_depIdxs,
		MessageInfos:      file_mesh_proto_msgTypes,
	}.Build()
	File_mesh_proto = out.File
	file_mesh_proto_goTypes = nil
	file_mesh_proto_depIdxs = nil
}
